config/routes.rb
Rails.application.routes.draw do
   
  root "areas#index"
  get "/sign_in" => "sessions#new", as: "sign_in"
  get 'promotions/search' => 'promotions#search'
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  resource :session, controller: "sessions", only: [:create, :new, :destroy ]
  
  resources :promotions
  resources :areas
  resources :partners
  resources :bookings
  resources :users
  resources :area, controller: "areas", only: [:show] do 
    resources :promotions, controller: "promotions", only: [:new, :create]
   end 
   
  resources :area, controller: "areas", only: [:show] do 
    resources :booking, controller: "bookings", only: [:new, :create, :show] do 
       post "checkout" 
    end 
  end 

  resources :user, controller: "users", only: [:show] do 
   resources :point_wallet, controller: "point_wallets", only: [:show]
  end 

   resources :promotions, controller: "promotions", only: [:show] do
      resources :point_wallet, controller: "point_wallets", only: [:show] do 
    resources :purchased_coupon, controller: "purchased_coupons", only: [:create, :new]
      end
    end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_one :area
  has_one :user
  has_one :point_wallet
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @area = Area.find(params[:area_id])
    @booking = Booking.find(params[:id])
    @client_token = Braintree::ClientToken.generate 
    @user = session[:user_id]
    # @user = @current_user 
    @promotion = Promotion.find_by(area_id: @booking.area_id)
    @purchased_coupon = PurchasedCoupon.find_by(point_wallet_id: @booking.point_wallet_id)
    @total_price = @area.price_per_night * ((@booking.check_out - @booking.check_in)/86400)
    

  end

  # GET /bookings/new
  def new
    @booking = Booking.new
    @area = Area.where(id: params[:area_id])
    @pointwallet_id = PointWallet.where(user_id: current_user.id)[0].id
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
    @user = @current_user
    # @purchased_coupon 
    @hello = 25
    @booking.update(purchased_coupon_id: @hello)
    # @booking(coupon_params).update
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @pointwallet_id = PointWallet.where(user_id: current_user.id)[0].id
    @booking.point_wallet_id = @pointwallet_id 
    @area = Area.find(params[:booking][:area_id])
    @point_wallet = PointWallet.find(params[:booking][:point_wallet_id])


    respond_to do |format|
      if @booking.save
        format.html { redirect_to area_booking_url(@area,@booking) }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end


  def checkout 
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    @area = Area.find(params[:area_id])
    @booking = Booking.find(params[:booking_id])
    @booking.total_price = @area.price_per_night * ((@booking.check_out - @booking.check_in)/86400)
    @booking.purchased_coupon_id = params[:purchased_coupon_id]
    @booking.discounted_price = params[:discount_price]
    @booking.update(total_price: @booking.total_price, purchased_coupon_id: @booking.purchased_coupon_id, discounted_price: @booking.discounted_price)
    @pointwallet = current_user.point_wallet

    @user = current_user
    @partner = Partner.where(id: 
      Area.where(id: @area)[0].partner_id)[0]


    if @booking.purchased_coupon_id != nil  
      result = Braintree::Transaction.sale(
      :amount => @booking.discounted_price,
      :payment_method_nonce => nonce_from_the_client,
      :options => {
        :submit_for_settlement => true 
       }
      )
    else 
        result = Braintree::Transaction.sale(
        :amount => @booking.total_price,
        :payment_method_nonce => nonce_from_the_client,
        :options => {
          :submit_for_settlement => true 
         }
        )
    end 

    if result.success?
       redirect_to :root, notice: "Transaction successful. Please check your email inbox."
      BookingMailer.partner_booking_email(@user, @partner, @booking).deliver_now
      BookingMailer.customer_booking_email(@user, @partner, @booking).deliver_now

      if @booking.purchased_coupon_id != nil  
          @pointwallet.update(earned: @booking.discounted_price) 
      else 
          @pointwallet.update(earned: @booking.total_price) 
      end 
     
    else
       redirect_to :root, notice: "Transaction failed. Please try again."
    end 
  end 

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:area_id, :point_wallet_id, :check_in, :check_out, :total_price)
    end

    # def coupon_params
    #     params.require(:booking).permit(:purchased_coupon_id)
    # end 


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_couponform.html.erb
  
  <% if  PurchasedCoupon.where(point_wallet_id: @booking.point_wallet_id).any? %> 
  <strong><%= Promotion.where(area_id: @booking.area_id)[0].name %></strong> coupon <br>
    purchased on <%= PurchasedCoupon.where(point_wallet_id: @booking.point_wallet_id)[0].created_at.to_date %> <br>
  <% else %> 
    no promotion coupon has been purchased for this property. <br>
  <% end %> 
</div>


<%= form_with(model: @booking, local: true) do |form| %>

  <div class="field">
    hello hidden field
    <%= form.hidden_field :purchased_coupon_id, value: 35 %>
      </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :area_id, value: params[:area_id] %> 
  </div>

  <div class="field">
    <%= form.hidden_field :point_wallet_id, value: @pointwallet_id %>


  </div>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.datetime_select :check_in, id: :booking_check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.datetime_select :check_out, id: :booking_check_out %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/edit.js.erb
$('#task-form').html("<%= j (render 'couponform') %>");
$('#task-form').slideDown(350);

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Area</th>
      <th>Point wallet</th>
      <th>Check in</th>
      <th>Check out</th>
      <th>Total price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.area_id %></td>
        <td><%= booking.point_wallet_id %></td>
        <td><%= booking.check_in %></td>
        <td><%= booking.check_out %></td>
        <td><%= booking.total_price %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<div class="col-md-6 col-sml-6">
 <strong><%= @area[0].location %></strong><br> 
  <%= @area[0].room_type %><br> 
  <%= @area[0].num_of_guest %> guests <br>
  $<%= @area[0].price_per_night %> per night <br>
  <%= image_tag @area[0].avatar_url(:medium).to_s %> <br>
</div>

<div class="col-md-6 col-sml-6">
 <%= render 'form', booking: @booking %>
</div>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<hr>
<!-- generate client token & embed in javascript -->
<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>


 <div class="col-md-6 col-sml-6">
  <strong><%= @area.location %></strong><br> 
  <%= @area.room_type %> <br>
  <%= @area.price_per_night %> per night<br> 
  <%= @area.num_of_guest %> guests <br>
  <%= image_tag @area.avatar_url(:medium).to_s %> 

  <hr>
  <strong>total day(s)</strong>
  <%= (@booking.check_out - @booking.check_in)/86400 %> days

  <hr>
  <strong>Total price:</strong>
  $<%= @area.price_per_night  %> * <%= (@booking.check_out - @booking.check_in)/86400 %> day(s) | 
   $<%= @total_price %><br>
   Earn <%= @total_price %> points with this booking <br>



<% if @promotion != nil %>
  <strong>Coupon applied price:</strong>
  <%= @promotion.name %> |
   <% if @promotion.reward_type == "discount" %> 
    $<%= @total_price - (@total_price * @promotion.value)/100 %> <br>
    Earn $<%= @total_price - (@total_price * @promotion.value)/100 %> points when booking at discounted price
   <% elsif @promotion.reward_type == "deduction" %> 
    $<%= @total_price -  @promotion.value %> <br>
    Earn <%= @total_price -  @promotion.value %> points with this booking when booking at discounted price. 
   <% end %> 
     <% if @purchased_coupon.promotion_id == @promotion.id  %> 
      <button onclick="myFunction()">apply coupon</button>
      <p id="applied"></p>
      <% else %> 
      <p>Coupon available. <%= link_to 'purchase', promotions_path %></p>
      <% end %>
 <% end %>

  
</div>

<div class = "col-md-6 col-sm-6">
  <div class= "demo-frame">
    <%= form_for :checkout_form, url: area_booking_checkout_path(@area, @booking), html: {id: "cardForm"} do |form| %> 

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"}  %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id ="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>
     <!-- <#%= hidden_field_tag(:purchased_coupon_id, @promotion.id ) %> -->
     <div id="coupon"></div>
     <div id="discount_price"></div>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %> 
    </div>
    <% end %> 
  </div>
</div>


<% if @purchased_coupon != nil %> 
  <script type="text/javascript">
    function myFunction() {
      document.getElementById("coupon").innerHTML = "<%= j hidden_field_tag(:purchased_coupon_id, @purchased_coupon.id) %>";
      document.getElementById("discount_price").innerHTML = "<%= j hidden_field_tag(:discount_price, 
        if @promotion.reward_type == "discount"
          @total_price - (@total_price * @promotion.value)/100
       elsif @promotion.reward_type == "deduction" 
         @total_price -  @promotion.value 
       end
       ) %>";
      document.getElementById("applied").innerHTML = "Coupon has been successfully applied.";
  }
  </script>
<% end %> 

<div class="col-md-12 col-sm-12">
<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'cancel', bookings_path %>
</div>




<script type="text/javascript">

 var form = document.querySelector('#cardForm');
 var submit = document.querySelector('#submit-payment-btn');
 var authorization = '<%= @client_token%>';

      braintree.client.create({
        authorization: authorization 
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          // console.error(clientErr); Q1 
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            // console.error(hostedFieldsErr);  Q2  displays the error message
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();



            // step 3(braintree picture)
            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              
              form.submit();
            });
          }, false);
        });
      });


</script>

app/views/bookings/show.js.erb
$(document).ready(function(){
  var one = document.getElementById("#one");
  // one.addEventListener("click", function(){
  //   console.log("hello"); 
  });

}