config/routes.rb
Rails.application.routes.draw do
   
  root "areas#index"
  get "/sign_in" => "sessions#new", as: "sign_in"
  get 'promotions/search' => 'promotions#search'
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  resource :session, controller: "sessions", only: [:create, :new, :destroy ]
  
  resources :promotions
  resources :areas
  resources :partners
  resources :bookings
  resources :users
  resources :area, controller: "areas", only: [:show] do 
    resources :promotions, controller: "promotions", only: [:new, :create]
   end 
   
  resources :area, controller: "areas", only: [:show] do 
    resources :booking, controller: "bookings", only: [:new, :create, :show] do 
       post "checkout" 
    end 
  end 

  resources :user, controller: "users", only: [:show] do 
   resources :point_wallet, controller: "point_wallets", only: [:show]
  end 

   resources :promotions, controller: "promotions", only: [:show] do
      resources :point_wallet, controller: "point_wallets", only: [:show] do 
    resources :purchased_coupon, controller: "purchased_coupons", only: [:create, :new]
      end
    end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_many :bookings
  has_many :promotions
  has_one :partner
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    @current_user = current_user
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @pointwallet = PointWallet.find_by(user_id: current_user.id)
    @area = Area.find(params[:id])
    @promotion = Promotion.find_by(area_id: @area.id)
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)
    @area.partner_id = current_user.id
    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    byebug
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:room_type, :num_of_guest, :price_per_night, :location, :avatar)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_type %>
    <%= form.text_field :room_type, id: :area_room_type %>
  </div>

  <div class="field">
    <%= form.label :num_of_guest %>
    <%= form.number_field :num_of_guest, id: :area_num_of_guest %>
  </div>

  <div class="field">
    <%= form.label :price_per_night %>
    <%= form.number_field :price_per_night, id: :area_price_per_night %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :area_location %>
  </div>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, id: :area_avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

  <h2 style="text-align: center"><%= link_to 'list your hotel', new_area_path if @current_user.class == Partner %></h2>

  <% @areas.each do |area| %>
  <div class="col-md-4 col-sm-6">
    <div class="hotel box">
      <strong><%= area.location %></strong><br>
      <%= area.room_type %> room <br>
      <%= area.num_of_guest %> guests |
      $<%= area.price_per_night %> per night <br>
      <%= image_tag area.avatar_url(:small).to_s %><br>
      <% if @current_user != nil %> 
        <%= link_to 'book this place', new_area_booking_path(area.id) if @current_user.class == User  %> | 
        <%= link_to 'details', area  %>
      <% end %>
      </tr>
    </div>
  </div>
  <% end %>


<br>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>


<!-- <#%= link_to 'book this place', new_area_point_wallet_booking_path(@area, @pointwallet) if session[:user_id] != nil? %> -->

 <!-- session[:user_id] != nil? -->

<!-- <#%= link_to 'redeem coupon', new_promotion_point_wallet_purchased_coupon_path(@promotion, @point_wallet) if @current_user.class == User %> -->


<div class="col-md-6 col-sm-6" style="text-align: center;">

    <h3><strong><%= @area.location %></strong><br></h3>
      <%= image_tag @area.avatar_url(:medium).to_s %> 
    <hr>
   <p>
    <%= @area.room_type %> room <br>
    <%= @area.num_of_guest %> guests <br>
    $<%= @area.price_per_night %> per night <br> 
    Promotion available? 
    <% if @promotion != nil %>
     <%= @promotion.name %><br>
     <%= @promotion.point %> points<br>
    <% else %>
      No promotion available. <%= link_to 'create now!', new_area_promotion_path(@area) if @current_user.id == @area.partner_id %>
    <% end %> 
    </p>
    <%= link_to 'book this place', new_area_booking_path(@area) if @current_user.class == User  %>
  </div>
</div>


<div class="col-md-12 col-sm-12" style="text-align: center;">
<%= link_to 'create promotion', new_area_promotion_path(@area) if current_user.id == @area.partner_id %>

</div>

<div class="col-md-12 col-sm-12" style="text-align: center;">

<%= link_to 'Hotel List', areas_path %>

</div>