config/routes.rb
Rails.application.routes.draw do
   
  root "areas#index"
  get "/sign_in" => "sessions#new", as: "sign_in"
  get 'promotions/search' => 'promotions#search'
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  resource :session, controller: "sessions", only: [:create, :new, :destroy ]
  
  resources :promotions
  resources :areas
  resources :partners
  resources :bookings
  resources :users
  resources :area, controller: "areas", only: [:show] do 
    resources :promotions, controller: "promotions", only: [:new, :create]
   end 
   
  resources :area, controller: "areas", only: [:show] do 
    resources :booking, controller: "bookings", only: [:new, :create, :show] do 
       post "checkout" 
    end 
  end 

  resources :user, controller: "users", only: [:show] do 
   resources :point_wallet, controller: "point_wallets", only: [:show]
  end 

   resources :promotions, controller: "promotions", only: [:show] do
      resources :point_wallet, controller: "point_wallets", only: [:show] do 
    resources :purchased_coupon, controller: "purchased_coupons", only: [:create, :new]
      end
    end 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/promotion.rb
class Promotion < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  has_one :area
  has_many :purchased_coupons

  scope :promo, -> (promo) {
    where('name ILIKE ? OR description ILIKE ?', "%#{promo}%","%#{promo}%")}


end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :set_promotion, only: [:show, :edit, :update, :destroy]

  # GET /promotions
  # GET /promotions.json
  def index
    @promotions = Promotion.all
    @areas = Area.all
    @current_user_id = session[:user_id]
    @point_wallet =  PointWallet.where(user_id: session[:user_id])[0]
  end

  # GET /promotions/1
  # GET /promotions/1.json
  def show
    @current_user_id = session[:user_id]
    @promotion = Promotion.find(params[:id])
    @point_wallet = PointWallet.find_by(user_id: current_user.id)
  end

  # GET /promotions/new
  def new
    @promotion = Promotion.new
  end

  # GET /promotions/1/edit
  def edit
  end

  def search 
     @promotions = Promotion.all
     @point_wallet = PointWallet.find_by(user_id: current_user).id
     filtering_params(params).each do |key, value|
     @promotions = @promotions.public_send(key, value) if value.present?
     end 
  end 

  # POST /promotions
  # POST /promotions.json
  def create
    @promotion = Promotion.new(promotion_params)
    @partner_id = session[:partner_id]
    respond_to do |format|
      if @promotion.save
        a = Partner.find_by(id: @partner_id)
        @promotion.update(promo: a.code + (0..9).to_a.sample(3).join)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully created.' }
        format.json { render :show, status: :created, location: @promotion }
      else
        format.html { render :new }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promotions/1
  # PATCH/PUT /promotions/1.json
  def update
    respond_to do |format|
      if @promotion.update(promotion_params)
        format.html { redirect_to @promotion, notice: 'Promotion was successfully updated.' }
        format.json { render :show, status: :ok, location: @promotion }
      else
        format.html { render :edit }
        format.json { render json: @promotion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotions/1
  # DELETE /promotions/1.json
  def destroy
    @promotion.destroy
    respond_to do |format|
      format.html { redirect_to promotions_url, notice: 'Promotion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promotion
      @promotion = Promotion.find(params[:id])
    end

    def filtering_params(params)
      params.slice(:name, :description, :promo)
     end 
    # Never trust parameters from the scary internet, only allow the white list through.
    def promotion_params
      params.require(:promotion).permit( :name, :reward_type, :value, :point, :description, :terms_conditions, :valid_from, :valid_to, :area_id)
    end
end

app/helpers/promotions_helper.rb
module PromotionsHelper
end

app/views/promotions/_form.html.erb
<%= form_with(model: promotion, local: true) do |form| %>
  <% if promotion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(promotion.errors.count, "error") %> prohibited this promotion from being saved:</h2>

      <ul>
      <% promotion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :promotion_name %>
  </div>

  <div class="field">
   <%= form.label :value %>
   <%= form.number_field :value, id: :promotion_value %>
  </div>

  <div class="field">
     <%= form.select(:reward_type) do %> 
      <% [['Promotion type', nil ], ['deduction(-)','deduction'],['discount(%)','discount']].each do |a| %> 
      <%= content_tag(:option, a.first, value: a.last) %>
      <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point, id: :promotion_point %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :promotion_description %>
  </div>

  <div class="field">
    <%= form.label :terms_and_conditions %>
    <%= form.text_area :terms_conditions, id: :promotion_terms_conditions %>
  </div>

  <div class="field">
    <%= form.label :valid_from %>
    <%= form.datetime_select :valid_from, id: :promotion_valid_from %>
  </div>

  <div class="field">
    <%= form.label :valid_to %>
    <%= form.datetime_select :valid_to, id: :promotion_valid_to %>
  </div>
  
  <%= form.hidden_field :area_id, value: params[:area_id] %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editing Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Show', @promotion %> |
<%= link_to 'Back', promotions_path %>

app/views/promotions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Promotions</h1>

<% if current_user.class == Partner %>
  <div class="col-md-12 col-sm-12">
    <%= form_tag(promotions_search_path, method: :get) do %> 
    <%= text_field_tag :promo, nil, placeholder:'find discounts!'  %>
    <%= submit_tag 'Search' ,name: nil , class: "btn btn-default search" %>
    <% end %>  
  </div>
<% end %>  

<% if current_user.class == User %> 
  <div class="wallet box">
   <h4><strong><%= link_to "my point wallet & rewards",  user_point_wallet_path( @current_user_id,@point_wallet.id) %></strong></h4>
    <%= @point_wallet.balance %> available points <br>
      <%= form_tag(promotions_search_path, method: :get) do %> 
      <%= text_field_tag :promo, nil, placeholder:'find discounts!'  %>
      <!--   <%#= hidden_field_tag(:point_wallet_id, @point_wallet.id ) %> -->
      <%= submit_tag 'Search' ,name: nil , class: "btn btn-default search" %>
      <% end %>  
  </div>
<% end %>

  <% @promotions.each do |promotion| %>
   <div class="col-md-4 col-sm-6">
    <div class="promotion box">
     <h4><strong><%= promotion.name %></strong></h4>
     <h4><%= promotion.promo %></h4>
     <strong>reward type</strong><br>
     <%= promotion.reward_type %>
     <%= promotion.point %> points <br>
     <strong>description</strong>
     <%= promotion.description %><br>
    <strong>terms and conditions</strong>
    <%= promotion.terms_conditions %><br>
     <strong>Valid date</strong>
     <%= promotion.valid_from.to_date %> ~ <%= promotion.valid_to.to_date %><br>
     <%= image_tag @areas.where(id: promotion.area_id)[0].avatar_url(:small).to_s %><br>
     <%= link_to 'purchase coupon', new_promotion_point_wallet_purchased_coupon_path(promotion, @point_wallet) if session[:user_id] != nil %>
      <% if session[:partner_id] !=nil   %> 
     <%= link_to 'Show', promotion %>
      <% end %> 
    </div>
   </div>
  <% end %>

<br>

app/views/promotions/new.html.erb
<h1>New Promotion</h1>

<%= render 'form', promotion: @promotion %>

<%= link_to 'Back', promotions_path %>

app/views/promotions/search.html.erb
<h1>search</h1>

<% for i in 0..@promotions.length - 1 %> 
  <div class="col-md-4 col-sm-6">
    <div class="promotion box">
      <strong><%= @promotions[i].name %></strong>
      <%= @promotions[i].promo %><br>
      <%= @promotions[i].reward_type %><br>
      <%= @promotions[i].point %><br>
      <%= @promotions[i].valid_from.to_date %> ~
      <%= @promotions[i].valid_to.to_date %><br>
      <%= link_to 'purchase coupon', new_promotion_point_wallet_purchased_coupon_path(@promotions[i], @point_wallet) %>
    </div>
   </div>
 <% end %> 

app/views/promotions/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'redeem coupon', new_promotion_point_wallet_purchased_coupon_path(@promotion, @point_wallet) if @current_user.class == User %>
<p>
  <strong>Name:</strong>
  <%= @promotion.name %>
</p>

<p>
  <strong>Reward type:</strong>
  <%= @promotion.value %> <%= @promotion.reward_type %>
</p>

<p>
  <strong>Point:</strong>
  <%= @promotion.point %>
</p>

<p>
  <strong>Description:</strong>
  <%= @promotion.description %>
</p>

<p>
  <strong>Terms conditions:</strong>
  <%= @promotion.terms_conditions %>
</p>

<p>
  <strong>Valid from:</strong>
  <%= @promotion.valid_from %>
</p>

<p>
  <strong>Valid to:</strong>
  <%= @promotion.valid_to %>
</p>



<%= link_to 'Edit', edit_promotion_path(@promotion) %> |
<%= link_to 'Back', promotions_path %>